(* scripts/embed_spv.ml
   Not compiled: run with the `ocaml` toplevel from a dune rule (see
   shaders/dune), e.g.

     ocaml scripts/embed_spv.ml vk_test_shaders.ml \
       double_comp double.comp.spv \
       triangle_vert triangle.vert.spv \
       triangle_frag triangle.frag.spv

   Emits an OCaml source file binding each NAME to a `string` holding the raw
   bytes of the corresponding FILE (compiled SPIR-V binaries in this repo),
   for the `vk_test_shaders` library (module Vk_test_shaders) used by
   test/test_compute.ml and test/test_graphics.ml. *)

let read_all path =
  let ic = open_in_bin path in
  let len = in_channel_length ic in
  let buf = Bytes.create len in
  really_input ic buf 0 len;
  close_in ic;
  Bytes.unsafe_to_string buf

(* Emit a quoted OCaml string literal containing exactly the bytes of [s],
   using \xHH escapes so every byte value (including NUL and non-ASCII bytes
   found in a SPIR-V binary) round-trips exactly. Lines are wrapped with the
   OCaml "\<newline>" continuation escape (which contributes zero characters
   to the resulting string) purely so the generated .ml file doesn't contain
   one enormous line. *)
let emit_string_literal buf s =
  Buffer.add_char buf '"';
  String.iteri
    (fun i c ->
      if i > 0 && i mod 20 = 0 then Buffer.add_string buf "\\\n  ";
      Buffer.add_string buf (Printf.sprintf "\\x%02x" (Char.code c)))
    s;
  Buffer.add_char buf '"'

let fail msg =
  prerr_endline msg;
  prerr_endline
    "usage: ocaml embed_spv.ml OUTPUT.ml NAME1 FILE1 [NAME2 FILE2 ...]";
  exit 1

let rec emit_pairs buf = function
  | [] -> ()
  | [ _ ] -> fail "embed_spv.ml: NAME without a matching FILE argument"
  | name :: file :: tl ->
    let bytes = read_all file in
    if String.length bytes mod 4 <> 0 then
      fail
        (Printf.sprintf
           "embed_spv.ml: %s is %d bytes, not a multiple of 4 (not a valid \
            SPIR-V binary?)"
           file (String.length bytes));
    Buffer.add_string buf (Printf.sprintf "let %s : string =\n  " name);
    emit_string_literal buf bytes;
    Buffer.add_string buf "\n\n";
    emit_pairs buf tl

let () =
  match Array.to_list Sys.argv with
  | _ :: out_path :: rest when rest <> [] ->
    let buf = Buffer.create 65536 in
    Buffer.add_string buf
      "(* Generated by scripts/embed_spv.ml from shaders/*.spv -- do not \
       edit. *)\n\n";
    emit_pairs buf rest;
    let oc = open_out_bin out_path in
    output_string oc (Buffer.contents buf);
    close_out oc
  | _ -> fail "embed_spv.ml: missing arguments"
